name: Freedeck New Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --no-build --self-contained true --output ${{ github.workspace }}/Freedeck/bin/Release/net8.0/win-x64/publish /p:PublishSingleFile=true /p:RuntimeIdentifier=win-x64 /p:ReadyToRun=true /p:IncludeAllContentForSelfExtract=true /p:IncludeNativeLibsForSelfExtract=true

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Freedeck.exe
          path: ${{ github.workspace }}/Freedeck/bin/Release/net8.0/win-x64/publish
        
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ github.workspace }}/Freedeck/bin/Release/net8.0/win-x64/publish/Freedeck.exe